version: 2
jobs:
  build:
    working_directory: ~/app-name
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
           key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install -g karma-cli
      - save_cache:
           key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: angular-test
          command: npm test -- --single-run --no-progress